name: Setup Shell Wrapper
description: Set up a shell wrapper script for setting the actions shell from the environment.
author: Sander Vocke
branding:
   color: blue
   icon: box

runs:
  using: composite
  steps:
    - name: Setup
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
           export INSTALL_BAT="true"
        fi
        /bin/sh ./setup.sh
      working-directory: ${{ github.action_path }}