name: Setup Shell Wrapper
description: Set up a shell wrapper script for setting the actions shell from the environment.
author: Sander Vocke
branding:
   color: blue
   icon: box

inputs:
  verbose:
    description: 'Enable verbose output'
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Env setup for verbosity
      if: inputs.verbose == 'true'
      shell: bash
      run: |
        echo "__SETUP_SHELL_WRAPPER_VERBOSE=true" | tee -a $GITHUB_ENV
    
    - name: Setup
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
           export INSTALL_BAT="true"
        fi
        /bin/sh ./setup.sh
      working-directory: ${{ github.action_path }}