name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        shell: [ bash, sh ]
        container: [ null ]
        container_options: [ null ]
        include:
          - shell: bash
            container: quay.io/pypa/manylinux_2_28_x86_64
            container_options: "--user root --workdir /"
          - shell: bash
            container: quay.io/pypa/manylinux_2_28_x86_64
            container_options: "--workdir /"
          
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
      options: ${{ matrix.container_options }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup wrapper
      uses: ./
    - name: Print shell
      shell: wrap-shell.sh {0}
      env:
         WRAP_SHELL: ${{ matrix.shell }}
      run: |
        RESULT=$(ps -o comm= $$)
        echo "Running shell: $RESULT"
        if [ "$RESULT" != "${{ matrix.shell }}" ]; then
          echo "Expected: ${{ matrix.shell }}"
          exit 1
        fi